name: flutter_text_highlighting
description: Flutter Text Highlighting
version: 0.0.1
homepage: https://github.com/luiz-simples/flutter-text-highlighting.git
repository: https://github.com/luiz-simples/flutter-text-highlighting.git
issue_tracker: https://github.com/luiz-simples/flutter-text-highlighting/issues

environment:
  sdk: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
